export const SUMMIT = {
  POST_REQUEST: 'POST_SUMMIT_REQUEST',
  POST_SUCCESS: 'POST_SUMMIT_SUCCESS',
  POST_FAILED: 'POST_SUMMIT_FAILED',
  GET_REQUEST: 'GET_SUMMIT_REQUEST',
  GET_SUCCESS: 'GET_SUMMIT_SUCCESS',
  GET_FAILED: 'GET_SUMMIT_FAILED',
  DELETE_REQUEST: 'DELETE_SUMMIT_REQUEST',
  DELETE_SUCCESS: 'DELETE_SUMMIT_SUCCESS',
  DELETE_FAILED: 'DELETE_SUMMIT_FAILED'
}
